### PR TITLE
Polish names

### PR DESCRIPTION
**Pull request by twolodzko**

### CODE REVIEW

**Comment by koaning** [comment]
Hi all. I was on holiday, hence the delay. Let's review :)

**Comment by koaning** [comment]
@twolodzko this looks great! Thanks for the PR. 

Also -> the bash script in the readme is *much* appreciated 😄 👍

**Review by koaning — APPROVED** [review]

**Comment by koaning** [comment]
Oh one thing though. @twolodzko did you sign the CLA?

**Comment by twolodzko** [comment]
@koaning thanks. Yes, I signed it, but for some reason, GitHub considers pushes from my two machines as if they were made by a different person. I tried hacking this by doing git reset and forced push, but while it seems to be a single commit now, your CLA bot still considers those changes to be made by two people. So sorry but I have no way of convincing it that CLA was already signed :laughing:

**Pull request merged**
